/**
 * Directory snapshot from oceansideresidents.com (Plaza at Oceanside).
 * Board + residents for demo directory — not login accounts.
 */

export const OCEANSIDE_BOARD = [
  { last: "Yska", first: "Dugald", email: "dugaldyska@gmail.com" },
  { last: "Grittani", first: "Ralph", email: "ralph@rgcdesigngroup.com" },
  { last: "DiColo", first: "Robert", email: "Robertdicolo@icloud.com" },
  { last: "Carbone", first: "Piero", email: "Pierocarbone555@gmail.com" },
] as const;

export const OCEANSIDE_CONTACT = {
  address: "1 North Ocean Blvd, Pompano Beach, FL 33062",
  phone: "954-781-4800",
  email: "Support@oceanside.com",
} as const;

/** Resident directory rows (deduped by email). */
export const OCEANSIDE_RESIDENTS: Array<{
  last: string;
  first: string;
  email: string;
}> = [
  { last: "Zavik", first: "Cher", email: "czavik@czavik.com" },
  { last: "Yska", first: "Dugald", email: "dugaldyska@gmail.com" },
  { last: "Whisnant", first: "Amanda", email: "Amanda@iServants.com" },
  { last: "Wang", first: "Jimmy", email: "zjwang@yahoo.com" },
  { last: "Vaillancourt", first: "Jane", email: "Janev@valco.ca" },
  { last: "Tremblay", first: "Linda", email: "lindatremblay@protonmail.com" },
  { last: "Test", first: "Ahmed", email: "ahashim@effvision.com" },
  { last: "Tear", first: "Kevin", email: "kevin.tear.ocean@gmail.com" },
  { last: "Stoecker", first: "Thomas", email: "tjsroa@aol.com" },
  { last: "St-Jean", first: "Alain", email: "ct158@oricom.ca" },
  { last: "Sobhy", first: "Sobhy", email: "mSobhy@effvision.com" },
  { last: "Singhal", first: "Radhey", email: "Raysinghal12@Gmail.com" },
  { last: "Singhal", first: "Niraj", email: "niraj@thesinghalgroup.com" },
  { last: "Shafei", first: "Mai", email: "mai@effvision.com" },
  { last: "Schneider", first: "Richard", email: "rickny72@aol.com" },
  { last: "Scheur", first: "Jill", email: "jill4feet@aol.com" },
  { last: "Scarafile", first: "Sicha", email: "sichapaul@hotmail.com" },
  { last: "Sacks", first: "David", email: "mrmarker31@gmail.com" },
  { last: "Russo", first: "Michelle", email: "mush5591@gmail.com" },
  { last: "Russo", first: "Lisa", email: "ljune22@aol.com" },
  { last: "Russell", first: "Randy", email: "randymon.0916@gmail.com" },
  { last: "Russell", first: "Deborah", email: "deborah.russell.0613@gmail.com" },
  { last: "Rondino", first: "Cindy", email: "crondino@icloud.com" },
  { last: "Roberts", first: "Elizabeth", email: "esr311@gmail.com" },
  { last: "Robbins", first: "Judy", email: "robbinsjm7@gmail.com" },
  { last: "Refino", first: "Jim", email: "jimr.mail@refino.com" },
  { last: "Price", first: "Natalie", email: "ndachille@me.com" },
  { last: "Price", first: "Aaron", email: "Price.2980@hotmail.com" },
  { last: "Polaski Lovesky", first: "Elaine", email: "epolaski@earthlink.net" },
  { last: "Pedneault", first: "Laurier", email: "laurierp@ccapitalinc.com" },
  { last: "Patel", first: "Taj", email: "Tajpatel@gptcommercial.com" },
  { last: "Passero", first: "Mark", email: "Mdp@passero.net" },
  { last: "O'Sullivan", first: "Kevin", email: "os@knowledgecompass.com" },
  { last: "Nowak", first: "Beata", email: "beata.nowak1@verizon.net" },
  { last: "Myers", first: "Teena", email: "skifun5@aol.com" },
  { last: "Mountain", first: "Peter", email: "peter_mountain@yahoo.com" },
  { last: "Mountain", first: "Lynne", email: "Lynnemountain@gmail.com" },
  { last: "Montpetit", first: "Benoit", email: "bm@thermo-stat.ca" },
  { last: "Michel", first: "Alain", email: "a.michel@videotron.ca" },
  { last: "Meyer", first: "Roy", email: "rmeyer@stcloudstate.edu" },
  { last: "Mason", first: "Victoria", email: "vickie@masonsemail.com" },
  { last: "Marucci", first: "Marygrace", email: "Marygrace1313@icloud.com" },
  { last: "Markovits", first: "Joan", email: "Jrmdsgn@yahoo.com" },
  { last: "Maher", first: "John", email: "MaherCPA@aol.com" },
  { last: "Maher", first: "Tracy", email: "tracymaher16@gmail.com" },
  { last: "Lyons", first: "Mary", email: "kenning356@gmail.com" },
  { last: "Lowe", first: "Stephen", email: "stevelo22@aol.com" },
  { last: "Lowe", first: "Harriet", email: "Hlowe930@gmail.com" },
  { last: "Loussia", first: "Carol", email: "cgloussia@comcast.net" },
  { last: "Levesque", first: "Jacques", email: "levesquj@sympatico.ca" },
  { last: "Lepof", first: "Joyce & Leah", email: "msjlep@aol.com" },
  { last: "Lee", first: "Robert", email: "bobbyleemiafl@aol.com" },
  { last: "Leblanc", first: "Daniel", email: "daniel@danielleblanc.com" },
  { last: "Leblanc", first: "Sarah", email: "sara.leblanc@hotmail.com" },
  { last: "Lapointe", first: "Andre", email: "andrelapointe@flapointe.com" },
  { last: "Laliberte", first: "Lise Jeanson", email: "Lise_laliberte@videotron.ca" },
  { last: "Kraft", first: "John", email: "johnekraft@comcast.net" },
  { last: "Kosches", first: "Dan", email: "apumpy@aol.com" },
  { last: "Kelly", first: "Robert", email: "rkelly123@gmail.com" },
  { last: "Johnson", first: "Susanne M", email: "theq5341@duck.com" },
  { last: "Janssen", first: "Bernardus (Ben)", email: "benjanssencn@yahoo.com" },
  { last: "Hofer", first: "Kerri Ann & Richard", email: "kerriann@me.com" },
  { last: "Himmel", first: "Barry", email: "bhimmel203@yahoo.com" },
  { last: "Hebert", first: "Francois", email: "francoishebert@hotmail.com" },
  { last: "Hajdu", first: "Regina", email: "Reginah714@gmail.com" },
  { last: "Habbu", first: "Ajit", email: "habbua@bellsouth.net" },
  { last: "Guida", first: "Marcia", email: "marcia.g.james@gmail.com" },
  { last: "Gruttadauria", first: "Joseph", email: "joegrutt@hotmail.com" },
  { last: "Gruttadauria", first: "Wendy", email: "Wendygrutt@hotmail.com" },
  { last: "Gavita", first: "Stephanie", email: "Stephgavita@yahoo.ca" },
  { last: "Fullum", first: "Carole", email: "carolesb16@gmail.com" },
  { last: "Foerster", first: "Robert", email: "bobfoerster54@gmail.com" },
  { last: "Foerster", first: "Judy", email: "judy81654@gmail.com" },
  { last: "Flynn", first: "Pat", email: "patmflynn2@gmail.com" },
  { last: "Flynn", first: "Vickie", email: "vfly68@gmail.com" },
  { last: "Fiet", first: "James", email: "jamesfiet58@gmail.com" },
  { last: "Ferchichi", first: "Farouk", email: "farferchichi@gmail.com" },
  { last: "Egeland", first: "Charlene M.", email: "charlene.egeland@gmail.com" },
  { last: "Durzo", first: "Luca", email: "Lucadurzo02@gmail.com" },
  { last: "Drive", first: "Murray", email: "14murraydrive@gmail.com" },
  { last: "Dougherty", first: "Robert and Mary Frances", email: "RDOUGHERTY4@VERIZON.NET" },
  { last: "DiChiazza", first: "Lina", email: "adichiazza@hotmail.com" },
  { last: "Di Chiazza", first: "Lorenzo", email: "Lorenzo@dmiprecision.com" },
  { last: "DeVirgilio", first: "John", email: "devirgilioj@yahoo.com" },
  { last: "DeVirgilio", first: "Beverly", email: "bevdevirgilio@gmail.com" },
  { last: "DeGuelle", first: "Ronald", email: "rondeguelle@hotmail.com" },
  { last: "Dachille", first: "Adolfo", email: "dachillechristie@yahoo.com" },
  { last: "Cuocolo", first: "Val", email: "vcuocolo@yahoo.com" },
  { last: "Cozzi", first: "Marietta", email: "marietta821@gmail.com" },
  { last: "Cook", first: "Edward", email: "edcook006@gmail.com" },
  { last: "Conti", first: "Janine", email: "jzirrith@wgcpas.com" },
  { last: "Clement", first: "Dan (and Liz)", email: "clements@ptd.net" },
  { last: "Clarizio", first: "Lisa Duragdata", email: "lisa@duragdata.com" },
  { last: "Clarizio", first: "Gaetano", email: "Guy@Luxury954.com" },
  { last: "Clarizio", first: "Lisa", email: "lisa@luxury954.com" },
  { last: "Chua", first: "Andrew", email: "ac.zhnith.mayon@gmail.com" },
  { last: "Chartrand", first: "Robert", email: "Marlenecoulombe@outlook.com" },
  { last: "Cendoya", first: "Alina", email: "cendoyaac@gmail.com" },
  { last: "Cefalo", first: "Benjamin", email: "bpcefalo@gmail.com" },
  { last: "Capussi", first: "Rosemarie", email: "Rose@jcfreshfarms.com" },
  { last: "Cadmus", first: "Ken", email: "kpcadmus@gmail.com" },
  { last: "Breton", first: "Guy", email: "guy.breton@umontreal.ca" },
  { last: "Black", first: "Elise", email: "Elise@theartists-studio.com" },
  { last: "Berchielli", first: "Diana", email: "dlbmer@aol.com" },
  { last: "Benson", first: "Sharlee", email: "sharbenson@yahoo.com" },
  { last: "Barbe", first: "Reginald", email: "barbe_reginald@yahoo.ca" },
  { last: "Mathieu", first: "David", email: "dlms6768@gmail.com" },
];
